var json = {
	"newHire1":  {
		'fname': 		['First Name:', 'Jessica'],
		'lname': 		['Last Name', 'MacDougall'],
		'hired': 		['Hire Date:', '11/01/2011'],
		'created': 		['Created On:', '11/04/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'position': 	['Position:', 'TechSupport'],
		'exp': 			['Experience Level:', '5'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '1234'],
		'repTag': 		['Rep Tag:', 'MJ234'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'jmacdougall'],
		'netPass': 		['Network Pass:', 'x10j3551c8m'],
		'emailid': 		['Email ID:', 'jessicam'],
		'emailPass': 	['Email Pass:', 'x10j3551c8m'],
		'emailAddress': ['Email Address:', 'jessicam@x10.com'],
		'pandionid': 	['Pandion User:', 'jessica.macdougall@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'macdougallj'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', 'Best Phone Rep']
	},
	"newHire2":  {
		'fname': 		['First Name:', 'Michael'],
		'lname': 		['Last Name', 'Youngblood'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'position': 	['Position:', 'IT'],
		'exp': 			['Experience Level:', '5'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2225'],
		'repTag': 		['Rep Tag:', 'YM225'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'myoungblood'],
		'netPass': 		['Network Pass:', 'x10m1ch83ly'],
		'emailid': 		['Email ID:', 'michaely'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'michaely@x10.com'],
		'pandionid': 	['Pandion User:', 'jessica.macdougall@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'macdougallj'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', 'the man']
	}

}