var json = {
	"e00001":  {
		'fname': 		['First Name:', 'Jessica'],
		'lname': 		['Last Name', 'MacDougall'],
		'hired': 		['Hire Date:', '11/21/2011'],
		'created': 		['Created On:', '11/22/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'TechSupport'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '37562'],
		'phoneExt': 	['Phone Ext:', '2613'],
		'repTag': 		['Rep Tag:', 'MJ613'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'jmacdougall'],
		'netPass': 		['Network Pass:', 'x10j3551c8m'],
		'emailid': 		['Email ID:', 'jessicamd'],
		'emailPass': 	['Email Pass:', 'x10j3551c8m'],
		'emailAddress': ['Email Address:', 'jessicamd@x10.com'],
		'pandionid': 	['Pandion User:', 'jessica.macdougall@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'macdougallj'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', 'Best Phone Rep Ever!']
	},
	"e00002":  {
		'fname': 		['First Name:', 'Michael'],
		'lname': 		['Last Name', 'Youngblood'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'Marketing'],
		'position': 	['Position:', 'WebDeveloper'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2225'],
		'repTag': 		['Rep Tag:', 'YM225'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'myoungblood'],
		'netPass': 		['Network Pass:', 'x10m1ch83ly'],
		'emailid': 		['Email ID:', 'michaely'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'michaely@x10.com'],
		'pandionid': 	['Pandion User:', 'jessica.macdougall@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'macdougallj'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', 'Its a me!']
	},
	"e00003":  {
		'fname': 		['First Name:', 'Aaron'],
		'lname': 		['Last Name', 'Beaudry'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'Sales'],
		'exp': 			['Experience Level:', '5'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2635'],
		'repTag': 		['Rep Tag:', 'BA635'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'abeaudry'],
		'netPass': 		['Network Pass:', 'x108b38udry'],
		'emailid': 		['Email ID:', 'aaronb'],
		'emailPass': 	['Email Pass:', 'x108b38udry'],
		'emailAddress': ['Email Address:', 'aaronb@x10.com'],
		'pandionid': 	['Pandion User:', 'aaron.beaudry@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'beaudrya'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', 'Came over when we closed Orca']
	},
	"e00004":  {
		'fname': 		['First Name:', 'Alexandria'],
		'lname': 		['Last Name', 'Cardenas'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'TechSupport'],
		'exp': 			['Experience Level:', '1'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2614'],
		'repTag': 		['Rep Tag:', 'CA614'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'acardenas'],
		'netPass': 		['Network Pass:', 'x108l3x8ndr18c'],
		'emailid': 		['Email ID:', 'alexandriac'],
		'emailPass': 	['Email Pass:', 'x108l3x8ndr18c'],
		'emailAddress': ['Email Address:', 'alexandriac@x10.com'],
		'pandionid': 	['Pandion User:', 'alexandria.cardenas@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'cardenasa'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', '']
	},
	"e00005":  {
		'fname': 		['First Name:', 'Andrew'],
		'lname': 		['Last Name', 'Packer'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'MiniSup'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2826'],
		'repTag': 		['Rep Tag:', 'PA826'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'apacker'],
		'netPass': 		['Network Pass:', 'x109ndr8wp'],
		'emailid': 		['Email ID:', 'andrewp'],
		'emailPass': 	['Email Pass:', 'x109ndr8wp'],
		'emailAddress': ['Email Address:', 'andrewp@x10.com'],
		'pandionid': 	['Pandion User:', 'andrew.packer@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'packera'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', 'The Pac-Man. Go to guy if you need support or have questions about old products.']
	},
	"e00006":  {
		'fname': 		['First Name:', 'Aneatra'],
		'lname': 		['Last Name', 'Harrison'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'TechSupport'],
		'exp': 			['Experience Level:', '6'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2638'],
		'repTag': 		['Rep Tag:', 'HA638'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'aharrison'],
		'netPass': 		['Network Pass:', 'x108n38tr8h'],
		'emailid': 		['Email ID:', 'aneatrah'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'aneatrah@x10.com'],
		'pandionid': 	['Pandion User:', 'aneatra.harrison@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'harrisona'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', '']
	},
	"e00007":  {
		'fname': 		['First Name:', 'Becky'],
		'lname': 		['Last Name', 'Fitzpatrick'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'OfficeManagement'],
		'position': 	['Position:', 'Receptionist'],
		'exp': 			['Experience Level:', '4'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2170'],
		'repTag': 		['Rep Tag:', 'FB170'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'bfitzpatrick'],
		'netPass': 		['Network Pass:', 'x10b3ckyf'],
		'emailid': 		['Email ID:', 'beckyf'],
		'emailPass': 	['Email Pass:', 'x10b3ckyf'],
		'emailAddress': ['Email Address:', 'beckyf@x10.com'],
		'pandionid': 	['Pandion User:', 'becky.fitzpatrick@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'fitzpatrickb'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', '']
	},
	"e00008":  {
		'fname': 		['First Name:', 'Ben'],
		'lname': 		['Last Name', 'Brockhaus'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'Marketing'],
		'position': 	['Position:', 'Copy Writer'],
		'exp': 			['Experience Level:', '7'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2210'],
		'repTag': 		['Rep Tag:', 'BB210'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'bbrockhaus'],
		'netPass': 		['Network Pass:', 'x10b3nb'],
		'emailid': 		['Email ID:', 'brockhaus'],
		'emailPass': 	['Email Pass:', 'x10b3nb'],
		'emailAddress': ['Email Address:', 'brockhaus@x10.com'],
		'pandionid': 	['Pandion User:', 'ben.brockhaus@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'brockhausb'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', '']
	},
	"e00009":  {
		'fname': 		['First Name:', 'Bill'],
		'lname': 		['Last Name', 'Phillips'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'TechSupport'],
		'exp': 			['Experience Level:', '3'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2615'],
		'repTag': 		['Rep Tag:', 'PB615'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'bphillips'],
		'netPass': 		['Network Pass:', 'x10b1llp'],
		'emailid': 		['Email ID:', 'billp'],
		'emailPass': 	['Email Pass:', 'x10b1llp'],
		'emailAddress': ['Email Address:', 'billp@x10.com'],
		'pandionid': 	['Pandion User:', 'bill.phillips@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'billp'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', '']
	},
	"e00010":  {
		'fname': 		['First Name:', 'Brandon'],
		'lname': 		['Last Name', 'Keeley'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'Marketing'],
		'position': 	['Position:', 'Director'],
		'exp': 			['Experience Level:', '4'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2222'],
		'repTag': 		['Rep Tag:', 'KB222'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'bkeeley'],
		'netPass': 		['Network Pass:', 'x10br8nd0nk'],
		'emailid': 		['Email ID:', 'brandonk'],
		'emailPass': 	['Email Pass:', 'x10br8nd0nk'],
		'emailAddress': ['Email Address:', 'brandonk@x10.com'],
		'pandionid': 	['Pandion User:', 'brandon.keeley@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'keeleyb'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', 'Director of Marketing']
	},
	"e00011":  {
		'fname': 		['First Name:', 'Connie'],
		'lname': 		['Last Name', 'Hicks'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'OrderProcessing'],
		'position': 	['Position:', 'OrderProcessing'],
		'exp': 			['Experience Level:', '4'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2707'],
		'repTag': 		['Rep Tag:', 'HC707'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'chicks'],
		'netPass': 		['Network Pass:', 'x10c0nn13h'],
		'emailid': 		['Email ID:', 'connieh'],
		'emailPass': 	['Email Pass:', 'x10c0nn13h'],
		'emailAddress': ['Email Address:', 'connieh@x10.com'],
		'pandionid': 	['Pandion User:', 'connie.hicks@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'hicksc'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', '']
	},
	"e00012":  {
		'fname': 		['First Name:', 'Dave'],
		'lname': 		['Last Name', 'Mayer'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'UpperManagement'],
		'position': 	['Position:', 'CEO'],
		'exp': 			['Experience Level:', '9'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2589'],
		'repTag': 		['Rep Tag:', 'MD589'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'dmayer'],
		'netPass': 		['Network Pass:', 'x10d8v3m'],
		'emailid': 		['Email ID:', 'davem'],
		'emailPass': 	['Email Pass:', 'x10d8v3m'],
		'emailAddress': ['Email Address:', 'davem@x10.com'],
		'pandionid': 	['Pandion User:', 'dave.mayer@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'mayerd'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', 'President/CEO']
	},
	"e00013":  {
		'fname': 		['First Name:', 'Dave'],
		'lname': 		['Last Name', 'Rye'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'Development'],
		'position': 	['Position:', 'VP'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2112'],
		'repTag': 		['Rep Tag:', 'RD112'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'drye'],
		'netPass': 		['Network Pass:', 'x10d8v3r'],
		'emailid': 		['Email ID:', 'daver'],
		'emailPass': 	['Email Pass:', 'x10d8v3r'],
		'emailAddress': ['Email Address:', 'daver@x10.com'],
		'pandionid': 	['Pandion User:', 'dave.rye@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'ryed'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', 'Sr. Vice President']
	},
	"e00014":  {
		'fname': 		['First Name:', 'Douglas'],
		'lname': 		['Last Name', 'Wiercinski'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'Director'],
		'position': 	['Position:', 'IT'],
		'exp': 			['Experience Level:', '4'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2110'],
		'repTag': 		['Rep Tag:', 'WD110'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'dwiercinski'],
		'netPass': 		['Network Pass:', 'x10d0ugl8s'],
		'emailid': 		['Email ID:', 'douglasw'],
		'emailPass': 	['Email Pass:', 'x10d0ugl8s'],
		'emailAddress': ['Email Address:', 'douglasw@x10.com'],
		'pandionid': 	['Pandion User:', 'douglas.wiercinski@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'wiercinskid'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', '']
	},
	"e00015":  {
		'fname': 		['First Name:', 'Eric'],
		'lname': 		['Last Name', 'Boyd'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'TechSupport'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2225'],
		'repTag': 		['Rep Tag:', 'YM225'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'eboyd'],
		'netPass': 		['Network Pass:', 'x10m1ch83ly'],
		'emailid': 		['Email ID:', 'ericb'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'ericb@x10.com'],
		'pandionid': 	['Pandion User:', 'eric.boyd@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'boyde'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', '']
	},
	"e00016":  {
		'fname': 		['First Name:', 'Evan'],
		'lname': 		['Last Name', 'Smith'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'inactive'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'IT'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2225'],
		'repTag': 		['Rep Tag:', 'YM225'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'esmith'],
		'netPass': 		['Network Pass:', 'x10m1ch83ly'],
		'emailid': 		['Email ID:', 'evans'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'evans@x10.com'],
		'pandionid': 	['Pandion User:', 'evan.smith@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'smithe'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', '']
	},
	"e00017":  {
		'fname': 		['First Name:', 'Greg'],
		'lname': 		['Last Name', 'Walker'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'CallCenter'],
		'position': 	['Position:', 'IT'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2225'],
		'repTag': 		['Rep Tag:', 'YM225'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'gwalker'],
		'netPass': 		['Network Pass:', 'x10m1ch83ly'],
		'emailid': 		['Email ID:', 'gregw'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'gregw@x10.com'],
		'pandionid': 	['Pandion User:', 'greg.walker@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'walkerg'],
		'os': 			['Stations OS:', 'WinXP'],
		'notes': 		['Notes:', '']
	},
	"e00018":  {
		'fname': 		['First Name:', 'Jacquie'],
		'lname': 		['Last Name', 'Voss'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'Financial'],
		'position': 	['Position:', 'Director'],
		'exp': 			['Experience Level:', '1'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2225'],
		'repTag': 		['Rep Tag:', 'YM225'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'jvoss'],
		'netPass': 		['Network Pass:', 'x10m1ch83ly'],
		'emailid': 		['Email ID:', 'jacquiev'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'jacquiev@x10.com'],
		'pandionid': 	['Pandion User:', 'jacquie.voss@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'vossj'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', '']
	},
	"e00019":  {
		'fname': 		['First Name:', 'Michael'],
		'lname': 		['Last Name', 'Youngblood'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'Default'],
		'position': 	['Position:', 'IT'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2225'],
		'repTag': 		['Rep Tag:', 'YM225'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'myoungblood'],
		'netPass': 		['Network Pass:', 'x10m1ch83ly'],
		'emailid': 		['Email ID:', 'michaely'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'michaely@x10.com'],
		'pandionid': 	['Pandion User:', 'jessica.macdougall@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'macdougallj'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', '']
	},
	"e00020":  {
		'fname': 		['First Name:', 'Michael'],
		'lname': 		['Last Name', 'Youngblood'],
		'hired': 		['Hire Date:', '05/08/2007'],
		'created': 		['Created On:', '05/08/2011'],
		'jobStatus': 	['Employee Status:', 'Active'],
		'department': 	['Department', 'Default'],
		'position': 	['Position:', 'IT'],
		'exp': 			['Experience Level:', '10'],
		'swipeid': 		['SwipeID:', '12345'],
		'phoneExt': 	['Phone Ext:', '2225'],
		'repTag': 		['Rep Tag:', 'YM225'],
		'vmpass': 		['Voice Mail Password:', '1234'],
		'compNumber': 	['Company Phone Number:', '(425) 203-3900'],
		'netid': 		['Network ID:', 'myoungblood'],
		'netPass': 		['Network Pass:', 'x10m1ch83ly'],
		'emailid': 		['Email ID:', 'michaely'],
		'emailPass': 	['Email Pass:', 'x10m1ch83ly'],
		'emailAddress': ['Email Address:', 'michaely@x10.com'],
		'pandionid': 	['Pandion User:', 'jessica.macdougall@sku.x10.com'],
		'pandionpass': 	['Pandion Pass:', 'macdougallj'],
		'os': 			['Stations OS:', 'Win7'],
		'notes': 		['Notes:', '']
	}

}